# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Product.create(name: "", description: "", long_description: "", ingredients: "", how_to_use: "", price: "", image_url: "")

Product.create(name: "Intensive Moisturising Lotion – Mama Kraus’s Miracle Cream", description: "A Pure Natural Intensive Body Lotion which is fragrance free and soothing. This all-over moisturiser can be used on your body, hands and face. It is made using only natural ingredients.", long_description: "This Natural Intensive Moisturising Lotion from our fragrance-free range is a fabulous moisturiser. We use only organic ingredients, these include Organic Shea Butter and Organic Olive Oil to help replenish and soothe your skin. This lotion is also know as Mama Kraus’s Miracle Cream. It contains minimal ingredients for those with allergic and sensitive skin types. A great fragrance free lotion.
Beeswax carries antiviral, anti-inflammatory, and antibacterial properties that are essential in fighting chapped skin and bacterial infections that tend to affect us most in the dry, winter months. It forms a protective wall by sealing in moisture in our skin without smothering and clogging up the pores.
Organic Olive Oil is packed with anti-ageing antioxidants and hydrating squalene, making it superb for hair, skin, and nails.
Organic Shea Butter as it is a great moisturiser which leaves skin feeling soft and supple. It also helps to keep your skin looking healthy and repairs dry and cracked skin.
You can use this natural body lotion on all skin types, but it is especially designed for those with sensitivity and allergies.
At CaTz~CreaTionZ we don’t put our products in outer packaging as this can be wasteful. This product is completely free from sodium laureath sulphate, parabens, phtalates and synthetic preservatives.", ingredients: "Intensive Moisturising Lotion – ingredients list.
distilled water, shea butter*, natural beeswax, virgin olive oil*  * denotes organic", how_to_use: "Apply lotion to clean skin and massage in thoroughly. Allow lotion to sink in.", price: "15", image_url: "moisturiserlotion.jpg")

Product.create(name: "Natural Coconut Oil Soap and Shampoo Bars", description: "Natural Coconut Oil Soap Bar is suited for all skin and hair types. It is a wonderful all over body wash as well as a shampoo bar. This bar is totally natural and unscented. It comes in a pack of 4 and each pack weighs between 390 – 400g.", long_description: "This Natural Coconut Oil Soap Bar makes a wonderful lather and leaves your skin feeling soft. It can also be used a s a shampoo bar.
Organic Coconut Oil is moisturising and easily absorbed. Coconut oil also contains properties that feed and hydrate your skin with additional antibacterial and antifungal benefits. Coconut oil is a powerful moisturizer that is beneficial to restoring dry or flaking skin as well.
Using the Natural Coconut Oil Soap Bar as a shampoo: Commercial shampoos are usually made with surfactants such as sodium lauryl sulfate – which is a known skin irritant that is often contaminated with the probable human carcinogen 1,4 dioxane – instead of soap. They also often contain silicone that coats the hair and prevents it from absorbing moisture. While silicone can make hair look smooth and shiny in the short-term, over time it causes it to dry out and become more brittle over time. When you make the switch to natural shampoo, you’re going from an approach that strips hair and then coats it with polymers to something that washes and nourishes the hair with a natural oil. During the transition you may find that your hair feels a little “gummy” – this can happen as silicone and other polymers begin to peel off. Another reason hair can seem dry or dull is that it soap is alkaline, and your hair prefers a more acidic environment. When washing with soap, you need to keep it happy by restoring hair pH with an acidic rinse* after shampooing. If used regularly, progressive results help encourage clean, manageable healthy hair and scalp, with the appearance of more body and thickness. Say goodbye to hair that appears dull, lifeless and dry.
*Apple Cider Rinse The rinse acts as a “conditioner” that balances pH, smooths the cuticle and makes your hair super shiny. In most cases you won’t need an additional conditioner, because shampoo bars moisturize while cleansing.
How to make and use Apple Cider Rinse: ¼ – ½ cup apple cider vinegar and enough filtered water to bring vinegar mixture to 3/4 cup. Mix ingredients. Pour over hair to saturate and allow to sit for 2-3 minutes, then rinse. Cool water will help the hair cuticle close, but warm is good too
**Please store your soap in a dry place and keep away from water.
At CaTz~CreaTionZ we don’t put our products in outer packaging as this can be wasteful. This product is completely free from sodium laureath sulphate, parabens, phtalates and synthetic preservatives.", ingredients: "Natural Coconut Oil Soap Bar – ingredients list. coconut oil *, distilled water, sodium hydroxide**, *denotes organic  ** none remains after saponifying oil into soap", how_to_use: "Using Natural Coconut Oil
Soap Bar Body Bar: You can use a washcloth by making it soapy with a few good rubs of soap or use your hands.
Shampoo Bar: Either first lather in your hands and then work from root to tip or rub the soap directly onto your hair to build up the lather you wish. Be careful, it will lather!! Apply to hair like all shampoos you would normally use.", price: "10", image_url: "plainsoap.jpg")

Product.create(name: "Rejuvenating Body Bar", description: "A Rejuvenating Body Bar which is fragrance free and soothing for rough skin such as elbows, knees, feet and hardworking hands. This bar is suitable for all skin types.", long_description: "This Rejuvenating Body Bar from our fragrance-free range is great to moisturise and nourish rough skin. We use only natural and organic ingredients. It contains minimal ingredients for those with allergic and sensitive skin types. Natural Beeswax carries antiviral, anti-inflammatory, and antibacterial properties that are essential in fighting chapped skin and bacterial infections that tend to affect us most in the dry, winter months. It forms a protective wall by sealing in moisture in our skin without smothering and clogging up the pores Organic Coconut Oil is moisturising and easily absorbed. Coconut oil also contains properties that feed and hydrate your skin with additional antibacterial and antifungal benefits. Organic Cacao Butter is rich in Vitamin E and fatty acids, it improves skin tone and elasticity. It is often used to soothe dry skin, rashes, eczema, scars, stretch marks, and psoriasis. You can use this Rejuvenating Body Bar on all skin types. At CaTz~CreaTionZ we don’t put our products in outer packaging as this can be wasteful. This product is completely free from sodium laureath sulphate, parabens, phtalates and synthetic preservatives.", ingredients: "Rejuvenating Body Bar – ingredients list. coconut oil*, beeswax, cacao butter*, * denotes organic", how_to_use: "Rejuvenating Body Bar. rub bar lightly on the desired area (elbows, feet, knees,hands etc.) then massage into skin as needed.", price: "10", image_url: "bodybar.jpg")

Product.create(name: "Enriching Day Moisturiser", description: "Enriching Day Moisturiser face cream is suitable for all skin types. It is made using only natural and organic ingredients.", long_description: "This wonderfully nourishing Enriching Day Moisturiser has been carefully designed to help maintain and replenish all skin types skin during the day with a light floral scent. Natural Beeswax carries antiviral, anti-inflammatory, and antibacterial properties that are essential in fighting chapped skin and bacterial infections that tend to affect us most in the dry, winter months. It forms a protective wall by sealing in moisture in our skin without smothering and clogging up the pores Organic Virgin Olive Oilis packed with anti-aging antioxidants and hydrating squalene, making it superb for hair, skin, and nails. Organic Coconut Oil is moisturising and easily absorbed. Coconut oil also contains properties that feed and hydrate your skin with additional antibacterial and antifungal benefits. Organic Lavender Essential Oil is added for its wonderful skin toning properties. Organic Frankincense Essential Oil is a powerful astringent, meaning it helps protect skin cells. It can be used to help reduce acne blemishes, the appearance of large pores, prevent wrinkles, and it even helps lift and tighten skin to naturally slow signs of aging. A wonderfully rich and replenishing Enriching Day Moisturiser to help your skin combat the dry environments of modern life! At CaTz~CreaTionZ we don’t put our products in outer packaging as this can be wasteful. This product is completely free from sodium laureath sulphate, parabens, phtalates and synthetic preservatives.", ingredients: "Enriching Day Moisturiser – ingredients list. distilled water, coconut oil*, beeswax, olive oil*, lavender essential oil*, frankincense essential oil*, tea tree essential oil* * denotes organic", how_to_use: "Enriching Day Moisturiser. Apply lotion to clean skin and massage in thoroughly. Allow lotion to sink in.", price: "12", image_url: "enrichday.jpg")


